name: Build latest videos

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * 5,6,7 *'

jobs:
  build-video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install NPM
        run: npm install --frozen-lockfile

      - name: Install ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Build Video
        run: npm run daily-video-build

      - name: Push to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync ./static/videos s3://videos --endpoint-url https://${{secrets.CF_ACCOUNT_ID}}.r2.cloudflarestorage.com --exclude"*.DS_Store"
